# Generated by Django 5.1.6 on 2025-03-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='connection_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='platform_account_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='token_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='platformtype',
            name='icon_class',
            field=models.CharField(default='bi-box', max_length=50),
        ),
        migrations.AddField(
            model_name='platformtype',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformtype',
            name='platform_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='platformtype',
            name='required_scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='platformconnection',
            unique_together={('tenant', 'platform_type', 'platform_account_id')},
        ),
        migrations.CreateModel(
            name='ClientPlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_client_id', models.CharField(help_text='Client ID in the advertising platform', max_length=255)),
                ('platform_client_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to='website.client')),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_associations', to='website.platformconnection')),
            ],
            options={
                'unique_together': {('client', 'platform_connection', 'platform_client_id')},
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('platform_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.platformtype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_settings', to='website.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'platform_type')},
            },
        ),
    ]
