# Generated by Django 5.1.6 on 2025-03-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_platformconnection_connection_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtype',
            name='position',
            field=models.PositiveIntegerField(default=100, help_text='Display order (lower numbers appear first)'),
        ),
    ]
