# Generated by Django 5.1.6 on 2025-03-03 18:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_platformtype_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('campaign_type', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('targeting_locations', models.TextField(blank=True, null=True)),
                ('ad_rotation', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_campaigns', to='website.clientplatformaccount')),
            ],
            options={
                'unique_together': {('client_account', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsAdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('ad_group_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='website.googleadscampaign')),
            ],
            options={
                'unique_together': {('campaign', 'ad_group_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='website.googleadscampaign')),
            ],
            options={
                'unique_together': {('campaign', 'date')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('date_range', models.CharField(default='LAST_30_DAYS', max_length=50)),
                ('date_range_days', models.IntegerField(default=30)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_cpc', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_daily_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('clicks_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ctr_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cost_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_cpc_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('conversions_change', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.googleadsadgroup')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.googleadscampaign')),
            ],
            options={
                'unique_together': {('campaign', 'ad_group', 'date_range')},
            },
        ),
    ]
