# Generated by Django 5.1.6 on 2025-03-05 15:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_clientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_model_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ecommerce', 'E-commerce (online product sales)'), ('lead_gen', 'Lead Generation (form submissions, calls, inquiries)'), ('marketplace', 'Marketplace (platform connecting buyers/sellers)'), ('subscription', 'Subscription/SaaS (recurring revenue model)'), ('brick_mortar', 'Brick & Mortar with Digital Presence'), ('service', 'Service-based Business (hourly/project billing)'), ('content', 'Content/Media (ad-supported)'), ('freemium', 'Freemium (free base product with paid upgrades)'), ('nonprofit', 'Non-profit/Donation-based'), ('b2b', 'B2B (business to business)'), ('b2c', 'B2C (business to consumer)'), ('b2g', 'B2G (business to government)'), ('d2c', 'D2C (direct to consumer)')], max_length=107, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_size',
            field=models.CharField(blank=True, choices=[('startup', 'Startup (1-10 employees)'), ('small', 'Small Business (11-50 employees)'), ('medium', 'Medium Business (51-200 employees)'), ('mid_market', 'Mid-Market (201-500 employees)'), ('large', 'Large Enterprise (501-1000 employees)'), ('enterprise', 'Enterprise (1000+ employees)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='geographic_focus',
            field=models.CharField(blank=True, choices=[('local', 'Local (single city/metropolitan area)'), ('regional', 'Regional (multi-city within state/province)'), ('state', 'State/Province-wide'), ('national', 'National'), ('multinational', 'Multi-national (select regions)'), ('global', 'Global')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marketing_maturity',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner (new to digital marketing)'), ('building', 'Building (established basics, developing strategy)'), ('intermediate', 'Intermediate (consistent execution, basic analytics)'), ('advanced', 'Advanced (data-driven, multi-channel strategy)'), ('expert', 'Expert (sophisticated testing, integration, attribution)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='revenue_range',
            field=models.CharField(blank=True, choices=[('pre_revenue', 'Pre-revenue'), ('under_500k', 'Under $500K'), ('500k_1m', '$500K - $1M'), ('1m_5m', '$1M - $5M'), ('5m_10m', '$5M - $10M'), ('10m_50m', '$10M - $50M'), ('50m_100m', '$50M - $100M'), ('100m_500m', '$100M - $500M'), ('500m_1b', '$500M - $1B'), ('over_1b', 'Over $1B')], max_length=20, null=True),
        ),
    ]
