# Generated by Django 5.1.6 on 2025-03-05 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_clientgroup_category_type_clientgroup_category_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'is_active'], name='website_cli_tenant__b8e4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='website_cli_name_5a5cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='website_cli_created_a5283c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_size'], name='website_cli_company_6ab7e2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['revenue_range'], name='website_cli_revenue_15d69c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['geographic_focus'], name='website_cli_geograp_3729f1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['marketing_maturity'], name='website_cli_marketi_19936d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientgroup',
            index=models.Index(fields=['tenant', 'is_active'], name='website_cli_tenant__ccc711_idx'),
        ),
        migrations.AddIndex(
            model_name='clientgroup',
            index=models.Index(fields=['is_auto_generated'], name='website_cli_is_auto_1eea8a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientgroup',
            index=models.Index(fields=['category_type', 'category_value'], name='website_cli_categor_a970e5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientgroup',
            index=models.Index(fields=['tenant', 'is_active', 'is_auto_generated'], name='website_cli_tenant__323920_idx'),
        ),
        migrations.AddIndex(
            model_name='clientplatformaccount',
            index=models.Index(fields=['client', 'is_active'], name='website_cli_client__deff99_idx'),
        ),
        migrations.AddIndex(
            model_name='clientplatformaccount',
            index=models.Index(fields=['platform_connection', 'is_active'], name='website_cli_platfor_e7a4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientplatformaccount',
            index=models.Index(fields=['platform_client_id'], name='website_cli_platfor_332ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsadgroup',
            index=models.Index(fields=['campaign', 'status'], name='website_goo_campaig_40776f_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsadgroup',
            index=models.Index(fields=['ad_group_type'], name='website_goo_ad_grou_2cc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsadgroup',
            index=models.Index(fields=['last_synced'], name='website_goo_last_sy_94886b_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadscampaign',
            index=models.Index(fields=['client_account', 'status'], name='website_goo_client__78fd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadscampaign',
            index=models.Index(fields=['campaign_type'], name='website_goo_campaig_4c9c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadscampaign',
            index=models.Index(fields=['start_date'], name='website_goo_start_d_dbaba9_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadscampaign',
            index=models.Index(fields=['end_date'], name='website_goo_end_dat_1cb45f_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadscampaign',
            index=models.Index(fields=['last_synced'], name='website_goo_last_sy_d864a8_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsdailymetrics',
            index=models.Index(fields=['campaign', 'date'], name='website_goo_campaig_9412bd_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsdailymetrics',
            index=models.Index(fields=['date'], name='website_goo_date_dfa67a_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsmetrics',
            index=models.Index(fields=['campaign'], name='website_goo_campaig_7ab929_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsmetrics',
            index=models.Index(fields=['ad_group'], name='website_goo_ad_grou_8b176a_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsmetrics',
            index=models.Index(fields=['date_range'], name='website_goo_date_ra_c3a486_idx'),
        ),
        migrations.AddIndex(
            model_name='googleadsmetrics',
            index=models.Index(fields=['date_start', 'date_end'], name='website_goo_date_st_952a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['tenant', 'platform_type', 'is_active'], name='website_pla_tenant__98974d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['connection_status'], name='website_pla_connect_76c038_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['created_at'], name='website_pla_created_f94a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['token_expiry'], name='website_pla_token_e_cabaed_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtype',
            index=models.Index(fields=['slug'], name='website_pla_slug_80dd44_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtype',
            index=models.Index(fields=['is_available'], name='website_pla_is_avai_0f9d98_idx'),
        ),
        migrations.AddIndex(
            model_name='platformtype',
            index=models.Index(fields=['position'], name='website_pla_positio_f978ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['name'], name='website_ten_name_b235ee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='website_ten_is_acti_8ef58a_idx'),
        ),
    ]
