# Generated by Django 5.1.6 on 2025-03-07 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_client_website_cli_tenant__b8e4b2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom Period')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='website.client')),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='website.clientgroup')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='website.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('underspend', 'Underspend Alert'), ('overspend', 'Overspend Alert'), ('forecast', 'Forecast Alert')], max_length=20)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_email_enabled', models.BooleanField(default=True)),
                ('is_dashboard_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='website.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='website.budget')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='website.googleadscampaign')),
                ('platform_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='website.clientplatformaccount')),
                ('platform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.platformtype')),
            ],
        ),
        migrations.CreateModel(
            name='SpendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('platform_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_snapshots', to='website.budget')),
            ],
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['tenant', 'is_active'], name='website_bud_tenant__084730_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['client'], name='website_bud_client__d830b0_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['client_group'], name='website_bud_client__316cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['start_date', 'end_date'], name='website_bud_start_d_f73082_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', 'alert_type'], name='website_bud_budget__0bbbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['is_active'], name='website_bud_is_acti_0d2916_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['user'], name='website_bud_user_id_763a20_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget'], name='website_bud_budget__307886_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['platform_type'], name='website_bud_platfor_e72e40_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['platform_account'], name='website_bud_platfor_67b32c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['campaign'], name='website_bud_campaig_2009e6_idx'),
        ),
        migrations.AddIndex(
            model_name='spendsnapshot',
            index=models.Index(fields=['budget', 'date'], name='website_spe_budget__b2e28b_idx'),
        ),
        migrations.AddIndex(
            model_name='spendsnapshot',
            index=models.Index(fields=['date'], name='website_spe_date_9a4e2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spendsnapshot',
            unique_together={('budget', 'date')},
        ),
    ]
