# Generated by Django 5.1.6 on 2025-05-16 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_competitor_client_industry_client_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tags', to='website.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='website.googleadscampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='website.campaigntag')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaigntag',
            index=models.Index(fields=['tenant'], name='website_cam_tenant__ce7266_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntag',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='campaigntagassignment',
            index=models.Index(fields=['tag'], name='website_cam_tag_id_927f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntagassignment',
            index=models.Index(fields=['campaign'], name='website_cam_campaig_d9e423_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntagassignment',
            unique_together={('tag', 'campaign')},
        ),
    ]
