# Generated by Django 5.1.6 on 2025-07-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_campaigntag_campaigntagassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(help_text='Google Ads customer ID (with hyphens)', max_length=20)),
                ('raw_account_id', models.CharField(help_text='Google Ads customer ID (without hyphens)', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_manager', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('time_zone', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=0, help_text='Hierarchy level (0 = top level)')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('active', 'Active'), ('sync_error', 'Sync Error'), ('permission_denied', 'Permission Denied'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('sync_error_message', models.TextField(blank=True)),
                ('can_be_login_customer', models.BooleanField(default=False)),
                ('accessible_account_count', models.IntegerField(default=0)),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_accounts', to='website.googleadsaccount')),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_accounts', to='website.platformconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['platform_connection', 'is_manager'], name='website_goo_platfor_af212f_idx'), models.Index(fields=['platform_connection', 'parent_account'], name='website_goo_platfor_0b1cc4_idx'), models.Index(fields=['account_id'], name='website_goo_account_8d51e6_idx'), models.Index(fields=['raw_account_id'], name='website_goo_raw_acc_ac1f0e_idx'), models.Index(fields=['can_be_login_customer'], name='website_goo_can_be__372403_idx'), models.Index(fields=['last_synced'], name='website_goo_last_sy_6ec637_idx')],
                'unique_together': {('platform_connection', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsAccountSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_discovered', models.IntegerField(default=0)),
                ('accounts_updated', models.IntegerField(default=0)),
                ('accounts_added', models.IntegerField(default=0)),
                ('accounts_deactivated', models.IntegerField(default=0)),
                ('sync_status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sync_details', models.JSONField(blank=True, default=dict)),
                ('platform_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_syncs', to='website.platformconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['platform_connection', 'started_at'], name='website_goo_platfor_5c0355_idx'), models.Index(fields=['sync_status'], name='website_goo_sync_st_c2acaa_idx')],
            },
        ),
    ]
