# Generated by Django 5.1.6 on 2025-07-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_googleadsaccount_googleadsaccountsync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctr_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Target CTR percentage (e.g., 2.50 for 2.5%)', max_digits=5, null=True)),
                ('conversion_rate_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Target conversion rate percentage (e.g., 3.25 for 3.25%)', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='website.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'is_active'], name='website_cli_client__b69cec_idx'), models.Index(fields=['created_at'], name='website_cli_created_8105ab_idx')],
            },
        ),
    ]
