# Generated by Django 5.1.6 on 2025-08-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_add_performance_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('google_ads_sync', 'Google Ads Data Sync'), ('google_ads_backfill', 'Google Ads Data Backfill'), ('bulk_refresh', 'Bulk Data Refresh')], max_length=50)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('actual_duration', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_tasks', to='website.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', 'status'], name='website_bac_task_ty_3f2ac4_idx'), models.Index(fields=['tenant', 'status'], name='website_bac_tenant__a0d657_idx'), models.Index(fields=['created_at'], name='website_bac_created_0932b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsDataFreshness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('data_source', models.CharField(default='google_ads_api', max_length=50)),
                ('sync_duration', models.IntegerField(blank=True, null=True)),
                ('campaigns_synced', models.IntegerField(default=0)),
                ('metrics_records_created', models.IntegerField(default=0)),
                ('has_data', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.client')),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.clientplatformaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'last_synced'], name='website_goo_tenant__77cb66_idx'), models.Index(fields=['client', 'date_start', 'date_end'], name='website_goo_client__c3f38e_idx')],
                'unique_together': {('client_account', 'date_start', 'date_end')},
            },
        ),
    ]
