# Generated by Django 5.1.6 on 2025-08-01 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_backgroundtask_googleadsdatafreshness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientperformancegoal',
            name='cost_per_click_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target cost per click (e.g., 1.50 for $1.50)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientperformancegoal',
            name='cost_per_conversion_goal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target cost per conversion (e.g., 25.00 for $25.00)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clientperformancegoal',
            name='use_global_goals',
            field=models.BooleanField(default=False, help_text="Use tenant's global goals instead of client-specific goals"),
        ),
        migrations.CreateModel(
            name='TenantPerformanceGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctr_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Global CTR target percentage (e.g., 2.50 for 2.5%)', max_digits=5, null=True)),
                ('conversion_rate_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Global conversion rate target percentage (e.g., 3.25 for 3.25%)', max_digits=5, null=True)),
                ('cost_per_click_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Target cost per click (e.g., 1.50 for $1.50)', max_digits=10, null=True)),
                ('cost_per_conversion_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Target cost per conversion (e.g., 25.00 for $25.00)', max_digits=10, null=True)),
                ('goal_mode', models.CharField(choices=[('global', 'Use global goals for all clients'), ('client_specific', 'Use client-specific goals'), ('mixed', 'Use client-specific where set, global as fallback')], default='mixed', help_text='How to apply goals across clients', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_performance_goals', to='website.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='website_ten_tenant__f173fd_idx'), models.Index(fields=['created_at'], name='website_ten_created_a3984e_idx')],
            },
        ),
    ]
